const paragraphs = [
    "Everyone knows that paper is made from trees. But when one looks at trees, one cannot imagine that something so soft and fragile as the paper is made is so hard and strong. Plant materials such as wood are made of fibres known as cellulose. It is the primary ingredient in paper making. Raw wood is first converted into pulp consisting of a mixture of Cellulose, lignin, water and some chemicals. The pulp can be made mechanically through grinders or through chemical processes. Short fibres are produced by mechanical grinding. The paper produced in this way is weak and is used to make newspapers, magazines and phonebooks.",
	"Gardening is my favourite hobby. I own a small plot of land next to our house. I cultivate gardening there. Every day, I spend half an hour gardening. After returning from my morning walk, I go to my garden with a spade and a bucket of water. I prepare the soil, prune the plants, and water them. I also use insecticides and fertilisers. My heart leaps with joy when I see the plants swaying in the wind. I feel heavenly pleasure as I watch them grow day by day.",
	"Home is the place where we return to rest after a day's work, and where parents and children meet together and have a carefree and joyful time. Our family consists of three members-father, mother, and brother. We live in a rural area. It is free from the hustle and bustle of city life. It is especially famous for its scenic beauty. I am the most important member of the family. Everyone trusts my judgement and agrees to follow my suggestions.",
	"Plants are vital organisms that produce oxygen through photosynthesis, supporting life on Earth. They range from tiny mosses to towering trees, playing crucial roles in ecosystems. Plants provide food, medicine, and materials, sustaining human and animal life. They improve air quality, prevent soil erosion, and regulate the climate. By fostering biodiversity, plants are the foundation of a healthy, balanced environment.",
	"Animals are diverse living beings that inhabit almost every part of the Earth, from deep oceans to high mountains. They play essential roles in ecosystems as pollinators, predators, prey, and decomposers. Animals range from tiny insects to massive whales, exhibiting incredible adaptations for survival. They provide companionship, labor, and resources such as food, wool, and leather. Understanding and protecting animals is crucial for maintaining ecological balance and preserving biodiversity.",
	"Software is a collection of programs and data that enable computers to perform specific tasks. It comes in various forms, including system software like operating systems, application software for user tasks, and middleware that connects different systems. Software development involves coding, testing, and maintaining these programs to meet user needs. It powers everything from mobile apps and websites to enterprise systems and AI technologies. As a cornerstone of the digital age, software continuously evolves to enhance efficiency, innovation, and connectivity.",
	"Engineering is the application of science, mathematics, and technology to design, build, and innovate solutions to real-world problems. It encompasses diverse fields like civil, mechanical, electrical, software, and biomedical engineering. Engineers create infrastructure, machines, and systems that shape modern life, from bridges and buildings to computers and medical devices. Problem-solving, creativity, and precision are central to engineering, driving progress across industries. By addressing societal challenges, engineering plays a vital role in advancing technology and improving quality of life.",
	"A computer is an electronic device designed to process, store, and retrieve data, performing tasks based on instructions from software. It consists of hardware components like the processor, memory, and storage, and relies on software to execute operations. Computers come in various forms, from desktops and laptops to smartphones and supercomputers. They are essential tools for communication, data analysis, entertainment, and automation. By enabling advancements in countless fields, computers have become integral to modern life and technological progress.",
	"A laptop is a portable computer designed for convenience and mobility, combining a screen, keyboard, touchpad, and hardware components in a compact form. It is powered by a rechargeable battery and can be used for various tasks, such as work, education, gaming, and entertainment. Laptops come in different sizes and configurations, catering to diverse needs from basic computing to high-performance tasks. They offer wireless connectivity, making them ideal for on-the-go usage. With their versatility and efficiency, laptops have become an essential tool for personal and professional use.",
	"Python is a high-level, versatile programming language known for its simplicity and readability. Created by Guido van Rossum in 1991, it emphasizes code clarity with its easy-to-understand syntax. Python supports multiple programming paradigms, including procedural, object-oriented, and functional programming. It's widely used in web development, data analysis, artificial intelligence, scientific computing, and more. With a vast ecosystem of libraries and a strong community, Python is a favorite choice for beginners and experienced developers alike.",
	"Java is a versatile, object-oriented programming language developed by Sun Microsystems in 1995, now maintained by Oracle Corporation. It follows the principle of write once, run anywhere (WORA), enabling code to run on any platform with a Java Virtual Machine (JVM). Java is widely used for building web applications, enterprise software, mobile apps (especially Android), and backend systems. Known for its robustness, scalability, and security features, Java remains a popular choice for developers worldwide. Its extensive libraries and frameworks make it suitable for a wide range of applications.",
	"R is a programming language and software environment specifically designed for statistical computing and data visualization. Developed in the 1990s by Ross Ihaka and Robert Gentleman, it is widely used by statisticians, data scientists, and researchers for tasks like data analysis, modeling, and reporting. R offers a vast ecosystem of packages through CRAN (Comprehensive R Archive Network), enhancing its capabilities in areas like machine learning, bioinformatics, and finance. Its robust graphical tools enable users to create high-quality visualizations. R is open-source and fosters a strong community, making it a powerful tool for data-driven decision-making.",
];

